// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include "../inst/include/RcppNumerical.h"
#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

// fastLR_
Rcpp::List fastLR_(Rcpp::NumericMatrix x, Rcpp::NumericVector y, Rcpp::NumericVector start, double eps_f, double eps_g, int maxit);
RcppExport SEXP RcppNumerical_fastLR_(SEXP xSEXP, SEXP ySEXP, SEXP startSEXP, SEXP eps_fSEXP, SEXP eps_gSEXP, SEXP maxitSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type start(startSEXP);
    Rcpp::traits::input_parameter< double >::type eps_f(eps_fSEXP);
    Rcpp::traits::input_parameter< double >::type eps_g(eps_gSEXP);
    Rcpp::traits::input_parameter< int >::type maxit(maxitSEXP);
    __result = Rcpp::wrap(fastLR_(x, y, start, eps_f, eps_g, maxit));
    return __result;
END_RCPP
}
// integrate_rcpp_
Rcpp::List integrate_rcpp_(Rcpp::Function f, Rcpp::RObject args, double lower, double upper, int subdiv, double eps_abs, double eps_rel, bool stop_on_error, int rule);
RcppExport SEXP RcppNumerical_integrate_rcpp_(SEXP fSEXP, SEXP argsSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP subdivSEXP, SEXP eps_absSEXP, SEXP eps_relSEXP, SEXP stop_on_errorSEXP, SEXP ruleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::Function >::type f(fSEXP);
    Rcpp::traits::input_parameter< Rcpp::RObject >::type args(argsSEXP);
    Rcpp::traits::input_parameter< double >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< double >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type subdiv(subdivSEXP);
    Rcpp::traits::input_parameter< double >::type eps_abs(eps_absSEXP);
    Rcpp::traits::input_parameter< double >::type eps_rel(eps_relSEXP);
    Rcpp::traits::input_parameter< bool >::type stop_on_error(stop_on_errorSEXP);
    Rcpp::traits::input_parameter< int >::type rule(ruleSEXP);
    __result = Rcpp::wrap(integrate_rcpp_(f, args, lower, upper, subdiv, eps_abs, eps_rel, stop_on_error, rule));
    return __result;
END_RCPP
}
