# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integrate_rcpp_ <- function(f, args, lower, upper, subdiv, eps_abs, eps_rel, stop_on_error, rule) {
    .Call('RcppNumerical_integrate_rcpp_', PACKAGE = 'RcppNumerical', f, args, lower, upper, subdiv, eps_abs, eps_rel, stop_on_error, rule)
}

logistic_reg_ <- function(x, y) {
    .Call('RcppNumerical_logistic_reg_', PACKAGE = 'RcppNumerical', x, y)
}

